included:
  - "/Sources/"

whitelist_rules:
  - attributes
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - colon 
  - comma 
  - compiler_protocol_init
  - control_statement
  - discouraged_direct_init
  - dynamic_inline
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - fatal_error_message
  - first_where
  - force_cast 
  - force_try 
  - force_unwrapping
  - generic_type_name
  - implicit_getter
  - implicitly_unwrapped_optional
  - large_tuple
  - leading_whitespace
  - mark
  - multiline_parameters
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - return_arrow_whitespace
  - shorthand_operator
  - sorted_imports
  - switch_case_on_newline
  - syntactic_sugar
  - todo
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_name
  - unused_enumerated
  - yoda_condition

force_cast: warning
force_try:
  severity: warning
type_name:
  min_length: 2
  max_length:
    warning: 50
large_tuple:
  warning: 3
  error: 4
colon:
  flexible_right_spacing: true
  severity: error
closing_brace: error
operator_usage_whitespace: error
attributes: 
  severity: warning
opening_brace: error
first_where: error
object_literal: 
  severity: warning
trailing_newline: warning
trailing_semicolon: error
trailing_whitespace: error