# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hellonerd_pb2 as hellonerd__pb2


class HelloNerdStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/hellonerd.HelloNerd/SayHello',
                request_serializer=hellonerd__pb2.HelloRequest.SerializeToString,
                response_deserializer=hellonerd__pb2.HelloReply.FromString,
                )


class HelloNerdServicer(object):
    """Missing associated documentation comment in .proto file"""

    def SayHello(self, request, context):
        """Sends a quote
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloNerdServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=hellonerd__pb2.HelloRequest.FromString,
                    response_serializer=hellonerd__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hellonerd.HelloNerd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HelloNerd(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hellonerd.HelloNerd/SayHello',
            hellonerd__pb2.HelloRequest.SerializeToString,
            hellonerd__pb2.HelloReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
