name: Deploy Podspec
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.3.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: Deploy Podspec
      run: |
        gem install cocoapods
        gem install fastlane
        pod repo add-cdn cdn https://cdn.cocoapods.org/
        pod repo add postmates git@github.com:postmates/Specs.git
        fastlane run version_bump_podspec path:Dependency.podspec version_number:$(git describe --tags `git rev-list --tags --max-count=1` | sed -e "s/^v//")
        pod repo push postmates Dependency.podspec --allow-warnings